# Atribui versão padrão do Fedora para 44, porém pode ser sobrescrita
ARG FEDORA_VERSION=44

# Estágio de construção de módulos (pacotes kmod)
FROM quay.io/fedora/fedora-bootc:${FEDORA_VERSION} AS builder
RUN <<EOF 
# Altera modo do Shell
set -e
# Atualiza pacote kernel*
dnf upgrade -y 'kernel*' --refresh
# Instala Dev Tools do Kernel
dnf install -y kernel-devel openssl perl-devel mokutil keyutils --refresh
# Variável para versão do Kernel
KERNEL_VERSION="$(rpm -q kernel-core --queryformat '%{VERSION}-%{RELEASE}.%{ARCH}')"
# Habilita copr e config-manager no dnf
dnf install -y 'dnf5-command(config-manager)' 'dnf5-command(copr)'
# Repositórios
dnf copr enable -y sentry/xpadneo
dnf config-manager addrepo -y --from-repofile=https://negativo17.org/repos/fedora-nvidia.repo
# Instalação akmods dos Módulos
dnf install -y nvidia-driver nvidia-open nvidia-driver-cuda \
xpadneo --refresh
# Compilação dos módulos
akmods --force --kernels "$KERNEL_VERSION"
EOF

# Puxa argumento de cima
ARG FEDORA_VERSION

# Constrói imagem especificada do Fedora Silverblue em bootc
FROM quay.io/fedora/fedora-silverblue:${FEDORA_VERSION}
# Adiciona labels do ostree
LABEL ostree.bootable="true"
LABEL containers.bootc="1"
WORKDIR /tmp/build-context
# Flag opcional para ignorar Secure Boot
ARG SECUREBOOT_IGNORE=false
# Cria diretórios home
RUN mkdir -p /var/roothome /data /var/home
# Copia lista de pacotes e módulos compilados
COPY dnf* ./
COPY --from=builder /var/cache/akmods/nvidia/kmod-nvidia*.rpm ./
COPY --from=builder /var/cache/akmods/xpadneo/kmod-xpadneo*.rpm ./
# Ajustando diretórios para /usr/local e /opt para evitar problemas de permissão e facilitar a instalação dos pacotes
RUN <<EOF
rm -rf /opt
mkdir /var/opt
ln -s /var/opt /opt
mkdir /var/usrlocal
mv /usr/local /usr/local_old
ln -s /var/usrlocal /usr/local
mv /usr/local_old/* /usr/local/
rm -rf /usr/local_old
EOF
RUN <<EOF
# Repositórios
dnf copr enable sentry/xpadneo -y
dnf config-manager addrepo -y --from-repofile=https://negativo17.org/repos/fedora-uld.repo
dnf config-manager addrepo -y --from-repofile=https://negativo17.org/repos/fedora-nvidia.repo
dnf config-manager addrepo -y --from-repofile=https://nvidia.github.io/libnvidia-container/stable/rpm/nvidia-container-toolkit.repo
sed -i 's|^sslcacert=.*|sslcacert=/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem|' /etc/yum.repos.d/nvidia-container-toolkit.repo
# Remoção dos pacotes da lista
tr '\n' ' ' < dnf-remove-packages | xargs dnf remove -y
# Atualização de todos os pacotes
dnf upgrade -y --refresh
EOF
# Instalação dos kmods compilados
RUN <<EOF
# kmod-nvidia
dnf download nvidia-kmod-common nvidia-driver-cuda
rpm -vi --nodeps nvidia-kmod-common*.rpm
rpm -vi --nodeps nvidia-driver-cuda*.rpm
dnf -y install ./kmod-nvidia-*.rpm
rm -rvf nvidia-driver-cuda*.rpm
rm -rvf nvidia-kmod-common*.rpm
# kmod-xpadneo
dnf -y install ./kmod-xpadneo-*.rpm
EOF
# Instalação dos pacotes que estão fora da imagem padrão
RUN tr '\n' ' ' < dnf-install-packages-with-nvidia | xargs dnf install -y
# Etapa de cópia para os parâmetros de boot
COPY 10-nvidia-args.toml 11-rhgb-quiet-iommu-args.toml ./
RUN <<EOF
mv -v 11-rhgb-quiet-iommu-args.toml /usr/lib/bootc/kargs.d/11-rhgb-quiet-iommu-args.toml
mv -v 10-nvidia-args.toml /usr/lib/bootc/kargs.d/10-nvidia-args.toml
EOF
# Etapa de cópia para o Secure Boot
COPY secureboot/ ./secureboot/
COPY .anchor ./.anchor
RUN --mount=type=bind,source=.,target=/context <<EOF
if [ "$SECUREBOOT_IGNORE" = "false" ]; then
        set -e
        mkdir -p ./.anchor
        cp -r /context/.anchor/* ./ 2>/dev/null
        bash ./secureboot/sign-modules.sh
fi
EOF
# Fase de limpeza
RUN <<EOF
rm -rvf dnf* 
rm -rvf kmod-*.rpm
rm -rvf .anchor
rm -rvf secureboot
dnf clean all
rm -rfv /var/cache/* \
        /var/lib/* \
        /var/log/* \
        /var/tmp/* 
EOF
# Volta pra raiz
WORKDIR /
# Verificar por erros na imagem 
RUN bootc container lint