# Atribui versão padrão do Fedora para 44, porém pode ser sobrescrita
ARG FEDORA_VERSION=44

# Estágio de construção de módulos (pacotes kmod)
FROM quay.io/fedora/fedora-bootc:${FEDORA_VERSION} AS builder
RUN dnf upgrade -y 'kernel*' --refresh && \
dnf install -y kernel-devel openssl perl-devel mokutil keyutils --refresh && \
KERNEL_VERSION="$(rpm -q kernel-core --queryformat '%{VERSION}-%{RELEASE}.%{ARCH}')" && \
dnf install -y 'dnf5-command(config-manager)' && \
dnf install -y --nogpgcheck --repofrompath 'terra,https://repos.fyralabs.com/terra$releasever' terra-release && \
dnf install -y fedora-workstation-repositories && \
dnf config-manager setopt rpmfusion-nonfree-nvidia-driver.enabled=1 && \
dnf install -y akmod-nvidia-open xorg-x11-drv-nvidia-cuda \
xpadneo --refresh && \
akmods --akmod xpadneo --kernels "$KERNEL_VERSION" --force && \
akmods --akmod nvidia-open --kernels "$KERNEL_VERSION" --force

# Puxa argumento de cima
ARG FEDORA_VERSION

# Constrói imagem especificada do Fedora Silverblue em bootc
FROM quay.io/fedora/fedora-silverblue:${FEDORA_VERSION} as final
# Adiciona labels do ostree
LABEL ostree.bootable="true"
LABEL containers.bootc="1"
WORKDIR /tmp/build-context
# Flag opcional para ignorar Secure Boot
ARG SECUREBOOT_IGNORE=false
# Cria diretórios home
RUN mkdir -p /var/roothome /data /var/home
# Copia lista de pacotes e módulos compilados
COPY nvidia-open/dnf* dnf* ./
COPY --from=builder /var/cache/akmods/xpadneo/kmod-xpadneo*.rpm ./
COPY --from=builder /var/cache/akmods/nvidia-open/kmod-nvidia-open*.rpm ./
RUN dnf install -y --nogpgcheck --repofrompath 'terra,https://repos.fyralabs.com/terra$releasever' terra-release && \
dnf install -y fedora-workstation-repositories && \
dnf config-manager setopt rpmfusion-nonfree-nvidia-driver.enabled=1 && \
dnf config-manager addrepo -y --from-repofile=https://negativo17.org/repos/fedora-uld.repo && \
dnf config-manager addrepo -y --from-repofile=https://nvidia.github.io/libnvidia-container/stable/rpm/nvidia-container-toolkit.repo && \
sed -i 's|^sslcacert=.*|sslcacert=/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem|' /etc/yum.repos.d/nvidia-container-toolkit.repo && \
tr '\n' ' ' < dnf-remove-packages | xargs dnf remove -y && \
dnf upgrade -y --refresh
RUN rpm -iv --nodeps ./kmod-nvidia-open*.rpm && \
dnf -y install xorg-x11-drv-nvidia-cuda --setopt=install_weak_deps=False && \
dnf -y install ./kmod-xpadneo-*.rpm
RUN tr '\n' ' ' < dnf-install-packages-with-nvidia | xargs dnf install -y
COPY nvidia-open/2-nvidia-args.toml 1-kernel-cmdline-args.toml nvidia-open/nvidia-power-management.conf ./
RUN mv -v 1-kernel-cmdline-args.toml /usr/lib/bootc/kargs.d/1-kernel-cmdline-args.toml && \
mv -v 2-nvidia-args.toml /usr/lib/bootc/kargs.d/2-nvidia-args.toml && \
mv -fv nvidia-power-management.conf /usr/lib/modprobe.d/nvidia-power-management.conf
COPY secureboot/ ./secureboot/
RUN --mount=type=bind,source=.,target=/context \
/bin/bash -c 'if [ "$SECUREBOOT_IGNORE" = "false" ]; then \
        set -e; \
        mkdir -p ./.anchor; \
        cp -r /context/.anchor/* ./ 2>/dev/null; \
        bash ./secureboot/sign-modules.sh; \
fi'
# Fase de limpeza
RUN rm -rvf /tmp/build-context && \
dnf clean all && \
rm -rfv /var/cache/* \
        /var/lib/* \
        /var/log/* \
        /var/tmp/* 
# Volta pra raiz
WORKDIR /
# Verificar por erros na imagem 
RUN bootc container lint