# Atribui versão padrão do Fedora para 44, porém pode ser sobrescrita
ARG FEDORA_VERSION=44

# Estágio de construção de módulos (pacotes kmod)
FROM quay.io/fedora/fedora-bootc:${FEDORA_VERSION} AS builder
RUN dnf upgrade -y 'kernel*' --refresh && \
dnf install -y kernel-devel openssl perl-devel mokutil keyutils --refresh && \
KERNEL_VERSION="$(rpm -q kernel-core --queryformat '%{VERSION}-%{RELEASE}.%{ARCH}')" && \
dnf install -y 'dnf5-command(config-manager)' && \
dnf install -y --nogpgcheck --repofrompath 'terra,https://repos.fyralabs.com/terra$releasever' terra-release && \
dnf install -y xpadneo --refresh && \
akmods --force --kernels "$KERNEL_VERSION"

# Puxa argumento de cima
ARG FEDORA_VERSION

# Constrói imagem especificada do Fedora Silverblue em bootc
FROM quay.io/fedora/fedora-silverblue:${FEDORA_VERSION} as final
# Adiciona labels do ostree
LABEL ostree.bootable="true"
LABEL containers.bootc="1"
WORKDIR /tmp/build-context
# Flag opcional para ignorar Secure Boot
ARG SECUREBOOT_IGNORE=false
# Cria diretórios home
RUN mkdir -p /var/roothome /data /var/home
# Copia lista de pacotes e módulos compilados
COPY default/dnf* dnf* ./
COPY --from=builder /var/cache/akmods/xpadneo/kmod-xpadneo*.rpm ./
RUN dnf install -y --nogpgcheck --repofrompath 'terra,https://repos.fyralabs.com/terra$releasever' terra-release && \
dnf config-manager addrepo -y --from-repofile=https://negativo17.org/repos/fedora-uld.repo && \
tr '\n' ' ' < dnf-remove-packages | xargs dnf remove -y && \
dnf upgrade -y --refresh
RUN dnf -y install ./kmod-xpadneo*.rpm
RUN tr '\n' ' ' < dnf-install-packages-default | xargs dnf install -y
COPY 1-kernel-cmdline-args.toml ./default/3-nouveau-args.toml ./
RUN mv -v 1-kernel-cmdline-args.toml /usr/lib/bootc/kargs.d/1-kernel-cmdline-args.toml && \
mv -v 3-nouveau-args.toml /usr/lib/bootc/kargs.d/3-nouveau-args.toml
COPY secureboot/ ./secureboot/
RUN --mount=type=bind,source=.,target=/context \
/bin/bash -c 'if [ "$SECUREBOOT_IGNORE" = "false" ]; then \
        set -e; \
        mkdir -p ./.anchor; \
        cp -r /context/.anchor/* ./secureboot/; \
        bash ./secureboot/sign-modules.sh; \
fi'
# Fase de limpeza
RUN rm -rvf /tmp/build-context && \
dnf clean all && \
rm -rfv /var/cache/* \
        /var/lib/* \
        /var/log/* \
        /var/tmp/* 
# Volta pra raiz
WORKDIR /
# Verificar por erros na imagem 
RUN bootc container lint