WORKDIR /var/roothome
RUN dnf -y install meson git cmake glib2 glib2-devel gnome-software-devel && \
git clone https://github.com/tobexeon/gnome-software-plugin-bootc.git && \
cd ./gnome-software-plugin-bootc && \
meson setup builddir && \
meson compile -C builddir

RUN mkdir -p ./gs-bootc
COPY --from=builder /var/roothome/gnome-software-plugin-bootc/* ./gs-bootc
COPY scripts/gnome-software-bootc/* ./
RUN cd ./gs-bootc && \
cp ./libgs_plugin_bootc.so /usr/lib64/gnome-software/plugins-23/ && \
bash ../install-to-image.sh