name: Default Build

on:
  schedule:
    - cron: '0 6 * * *' # Constrói as 6:00
  push:
    branches: 
      - master
    paths-ignore:
      - '**.md'
  workflow_dispatch: # Permite rodar manualmente
env:
  IMAGE_NAME: ${{ github.event.repository.name }}
  REGISTRY: ghcr.io/${{ github.repository_owner }}


jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Log into GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Suporte a Secure Boot
        env:
          CERTIFICATE_BASE64: ${{ secrets.SECURE_BOOT_CERT }}
          PRIVATEKEY_BASE64: ${{ secrets.SECURE_BOOT_KEY }}
        run: |
            echo -n "$CERTIFICATE_BASE64" | wc -c
            echo -n "$PRIVATEKEY_BASE64" | wc -c
            mkdir -p .anchor
            echo -n "$CERTIFICATE_BASE64" | base64 --decode > .anchor/akmods.der
            echo -n "$PRIVATEKEY_BASE64" | base64 --decode > .anchor/akmods.priv
            openssl x509 -inform der -in .anchor/akmods.der -text -noout | grep "Subject:" || echo "ERRO: Certificado DER inválido"
            openssl pkey -in .anchor/akmods.priv -pubout -out /dev/null || echo "ERRO: Chave privada inválida ou requer senha"
            
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Containerfile # Ou Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:44
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
