name: nvidia-open build

on:
  schedule:
    - cron: '0 6 * * *' # Constrói as 6:00
  workflow_dispatch:
    inputs:
      fedora_version:
        description: 'Versão do Fedora Silverblue'
        default: '44'
        required: false

env:
  IMAGE_NAME: fedora-silverblue-bootc-custom-nvidia-open
  REGISTRY: ghcr.io/${{ github.repository_owner }}
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-push:
    runs-on: ubuntu-latest
    env:
      SELECTED_VERSION: ${{ github.event.inputs.fedora_version || '44' }}
      DEFAULT_VERSION: '44'
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    
      - name: Checkout Repo
        uses: actions/checkout@v4
        
      - name: Gerar metadados do build
        id: meta
        run: |
          VERSION=${{ env.SELECTED_VERSION }}
          DATE=$(TZ='America/Sao_Paulo' date +'%Y%m%d-%H%M')
          VERSIONANDDATE="${VERSION}-${DATE}"
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          if [ "${{ env.SELECTED_VERSION }}" -gt "${{ env.DEFAULT_VERSION }}" ]; then
            echo "channel=beta" >> $GITHUB_OUTPUT
          elif [ "${{ env.SELECTED_VERSION }}" -eq "${{ env.DEFAULT_VERSION }}" ]; then
            echo "channel=latest" >> $GITHUB_OUTPUT
          else
            echo "channel=old" >> $GITHUB_OUTPUT
          fi
          echo "version=${VERSION}"     >> $GITHUB_OUTPUT
          echo "short_sha=${SHORT_SHA}" >> $GITHUB_OUTPUT
          echo "versionanddate=${VERSIONANDDATE}"     >> $GITHUB_OUTPUT
          
      - name: Log into GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Assinatura  dos módulos  de kernel
        env:
          PRIVATEKEY_BASE64: ${{ secrets.SECURE_BOOT_KEY }}
        run: |
            mkdir -p .anchor
            echo -n "$PRIVATEKEY_BASE64" | base64 --decode > .anchor/MOK.priv
            
      - name: Build e Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./nvidia-open/Containerfile
          push: true
          build-args: |
            FEDORA_VERSION=${{ env.SELECTED_VERSION }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.SELECTED_VERSION }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.versionanddate }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.short_sha }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.channel }}
