name: nvidia-open build

on:
  schedule:
    - cron: '0 6 * * *' # Constrói as 6:00
  workflow_dispatch:
    inputs:
      fedora_version:
        description: 'Versão do Fedora Silverblue'
        default: '44'
        required: false

env:
  IMAGE_NAME: fedora-silverblue-bootc-custom-nvidia-open
  REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  build-push:
    runs-on: ubuntu-latest
    env:
      SELECTED_VERSION: ${{ github.event.inputs.fedora_version || '44' }}
      DEFAULT_VERSION: '44'
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Log into GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Suporte a Secure Boot
        env:
          CERTIFICATE_BASE64: ${{ secrets.SECURE_BOOT_CERT }}
          PRIVATEKEY_BASE64: ${{ secrets.SECURE_BOOT_KEY }}
        run: |
            mkdir -p .anchor
            echo -n "$CERTIFICATE_BASE64" | base64 --decode > .anchor/akmods.der
            echo -n "$PRIVATEKEY_BASE64" | base64 --decode > .anchor/akmods.priv

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Containerfile
          push: true
          build-args: |
            FEDORA_VERSION=${{ env.SELECTED_VERSION }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.SELECTED_VERSION }}
            ${{ (env.SELECTED_VERSION == env.DEFAULT_VERSION) && format('{0}/{1}:latest', env.REGISTRY, env.IMAGE_NAME) || '' }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
